# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dad1f730fd639513275fe4f2b3e24799f3d8060f4d5fa78eaeef7d3ba709169e9bd7e26353a7128ad4d17365b5f5f6781f10663fbc30f091d4731a800d78a67
  json_web_token_secret: 5d41402abc4b2a76b9719d911017c592

test:
  secret_key_base: fb3df681298a434c72d1c7583b7d56c0a120dfb96ad1879278260027d46c92fb32d7e69c3765401f277f5ac9b3b220d8f0c668edb83acf4236d261d4bd50a7b2
  json_web_token_secret: 5d41402abc4b2a76b9719d911017c592

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  json_web_token_secret: <%= ENV["JSON_WEB_TOKEN_SECRET"] %>
